yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
count_first_symbols = 15


class Post(models.Model):
    """Класс для постов"""

    text = models.TextField(verbose_name='Текст поста',
                            help_text='Семь раз отмерь, один раз напиши')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Сообщество'
    )
    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        """Возвращает начало текст поста"""
        return f'{self.text[:count_first_symbols]}'


class Group(models.Model):
    """Класс для сообществ"""

    title = models.CharField(max_length=200,
                             verbose_name='Название сообщества',
                             help_text='200 символов максимум')
    slug = models.SlugField(max_length=200,
                            unique=True,
                            verbose_name='Псевдоним сообщества',
                            help_text='200 символов максимум')
    description = models.TextField(verbose_name='Описание сообщества',
                                   help_text='Тематика постов')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        """Возвращает строку с названием сообщества"""
        return f'{self.title}'


class Comment(models.Model):
    """Класс для комментариев"""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария'
    )
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Пиши-сокращай. Максимум 1000 знаков')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата комментария')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created']
        default_related_name = 'comments'

    def __str__(self) -> str:
        """Возвращает начало текста комментария"""
        return f'{self.text[:count_first_symbols]}'


class Follow(models.Model):
    """Подписка на авторов"""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Фолловер'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='follow_unique',)
        ]

    def __str__(self) -> str:
        """Возвращает сообщение о подписке"""
        return f'{self.user} подписан на автора {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Форма поста для блога"""
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        """Валидация текста поста"""
        new_post_text = self.cleaned_data['text']
        if len(new_post_text) < 10:
            raise forms.ValidationError('Пост слишком короткий')
        elif 'кг/ам' in new_post_text:
            raise forms.ValidationError('Слишком грубо!')
        return new_post_text


class CommentForm(forms.ModelForm):
    """Форма комментария к посту"""
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'cols': 20, 'rows': 5}),
        }

    def clean_text(self):
        """Валидация текста комментария"""
        comment_text = self.cleaned_data['text']
        if len(comment_text) > 1000:
            raise forms.ValidationError('Многабукаф')
        elif 'кг/ам' in comment_text:
            raise forms.ValidationError('Слишком грубо!')
        return comment_text

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginate_queryset

POSTS_ON_PAGE = 10


def index(request):
    """Возвращает главную страницу приложения"""
    template = "posts/index.html"
    posts = Post.objects.select_related('author').select_related('group').all()
    page_obj = paginate_queryset(request, posts, POSTS_ON_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Принимает slug группы
    Возвращает страницу этого сообщества с последними ссобщениями
    """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author').all()
    page_obj = paginate_queryset(request, posts, POSTS_ON_PAGE)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Принимает username пользователя
    Возвращает страницу-профиль этого пользователя
    """
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=User.objects.get
                                          (username=username)).exists()
    user_object = get_object_or_404(User, username=username)
    user_posts = user_object.posts.select_related(
        'group').all().annotate(posts_count=Count('id'))
    page_obj = paginate_queryset(request, user_posts, POSTS_ON_PAGE)
    context = {
        'user_object': user_object,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Принимает post_id поста
    Возвращает страницу с деталями этого поста
    """
    post_object = get_object_or_404(Post.objects.select_related(
        'author').select_related('group'), id=post_id)
    is_author = False
    if request.user == post_object.author:
        is_author = True
    form = CommentForm(
        request.POST or None,
    )
    comments = post_object.comments.all()
    context = {
        'post_object': post_object,
        'is_author': is_author,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Создание нового поста"""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'form': form,
    }

    if request.method == 'POST':
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect(reverse('posts:profile',
                            kwargs={'username': request.user.username}))

        return render(request, 'posts/create_post.html', {'form': form})

    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста"""
    is_edit = True
    post_object = get_object_or_404(Post.objects.select_related(
        'author'), id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_object,
    )
    context = {
        'form': form,
        'is_edit': is_edit,
    }
    if request.user == post_object.author:
        if request.method == 'POST':
            if form.is_valid():
                post_object.text = form.cleaned_data['text']
                post_object.group = form.cleaned_data['group']
                post_object.save()
                return redirect(reverse('posts:post_detail',
                                kwargs={'post_id': post_object.id}))

            return render(request, 'posts/create_post.html',
                          {'form': form, 'is_edit': is_edit})

        return render(request, 'posts/create_post.html', context)
    return redirect((reverse('posts:post_detail',
                     kwargs={'post_id': post_object.id})))


@login_required
def add_comment(request, post_id):
    """Добавление комментария к посту"""
    post = get_object_or_404(Post.objects.select_related(
        'author'), id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Возвращает страницу постов любимых авторов"""
    user_object = request.user
    authors = user_object.follower.all().values_list('author', flat=True)
    posts = Post.objects.select_related('author').select_related(
        'group').filter(author__id__in=authors)
    template = "posts/follow.html"
    page_obj = paginate_queryset(request, posts, POSTS_ON_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора"""
    if request.user.username == username:
        return redirect('posts:profile', username=username)
    author = get_object_or_404(User, username=username)
    Follow.objects.get_or_create(user=request.user,
                                 author=author,
                                 )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора"""
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user,
                             author=author,
                             ).exists() is False:
        return redirect('posts:profile', username=username)
    Follow.objects.filter(user=request.user,
                          author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %} 
{% block content %}
{% with request.resolver_match.view_name as view_name %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}            
          </div>
          <div class="card-body">        
            {% load user_filters %}
            {% include 'includes/error_style.html' %}
            <form method="post" enctype="multipart/form-data">
              {% include 'includes/form_processing.html' %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endwith %} 
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Ваши любимые авторы
{% endblock %} 
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">     
    <h1>Посты от ваших любимых авторов</h1>
    </article>
    <hr>
      {% load cache %}
      {% include 'posts/includes/switcher.html' %}
      {% cache 20 follow_page %}
      {% for post in page_obj %}
        <article>
            <ul>
            <li>
              <b>Автор:</b> {{ post.author.first_name }} {{ post.author.last_name }}
            </li>
            <li>
              <b>Сообщество:</b> {{ post.group.title }}
            </li>
            <li>
              <b>Дата публикации:</b> {{ post.pub_date|date:"j F Y" }}
            </li>
            </ul>      
            <p>
              {% thumbnail post.image "1200x300" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              {{ post.text|safe }}
            </p>         
        </article>
        {% if post.group %}   
          <a href="{% url 'posts:group_posts' post.group.slug %}">
            Больше постов <b>{{ post.group.title }}</b> 
          </a>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
    {% endfor%}
    {% endcache %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
    {{ group }} - все записи
{% endblock %}   
{% block content %}
    {% load thumbnail %}
    <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>
        {{ group.description }}
    </p>
    {% for post in page_obj %}
        <article>
            <ul>
            <li>
              Автор: {{ post.author.first_name }} {{ post.author.last_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"j F Y" }}
            </li>
            </ul>      
            <p>
                {% thumbnail post.image "1200x300" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                {{ post.text|safe }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">Подробная информация о публикации</a>       
        </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
    {% endfor%}
    <br>
    <a href="{% url 'posts:index' %}"><b>На главную</b> </a>
    {% include 'posts/includes/paginator.html' %}
    </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Это главная страница проекта Yatube
{% endblock %} 
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    </article>
    <hr>
      {% load cache %}
      {% include 'posts/includes/switcher.html' %}
      {% cache 20 index_page %}
      {% for post in page_obj %}
        <article>
            <ul>
            <li>
              <b>Автор:</b> {{ post.author.first_name }} {{ post.author.last_name }}
            </li>
            <li>
              <b>Сообщество:</b> {{ post.group.title }}
            </li>
            <li>
              <b>Дата публикации:</b> {{ post.pub_date|date:"j F Y" }}
            </li>
            </ul>      
            <p>
              {% thumbnail post.image "1200x300" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              {{ post.text|safe }}
            </p>         
        </article>
        {% if post.group %}   
          <a href="{% url 'posts:group_posts' post.group.slug %}">
            Больше постов <b>{{ post.group.title }}</b> 
          </a>
        {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
    {% endfor%}
    {% endcache %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    Пост {{ post_object.text|slice:":30" }}
{% endblock %} 
{% block content %}
  {% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <b>Дата публикации:</b> {{ post_object.pub_date|date:"j F Y" }}
        </li>
        {% if post_object.group %} 
        <li class="list-group-item">
            <b>Группа:</b> {{ post_object.group }}
          <a href="{% url 'posts:group_posts' post_object.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
            <b>Автор:</b> {{ post_object.author.first_name }} {{ post_object.author.last_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <b>Всего постов автора:</b>  <span >{{ post_object.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_object.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_object.image "1200x300" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <div class="container">
        {{ post_object.text|safe }}
      {% if is_author %}
      <br><br>
      <a href="{% url 'posts:post_edit' post_object.id %}" class="btn btn-primary">
        редактировать запись
      </a>
      {% endif %} 
    </div>
    <br>
    <div> 
      {% include 'posts/includes/view_comments.html' %}
    </div> 
    <div> 
      {% include 'posts/includes/add_comment.html' %}
    </div>
  </article> 
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{ user_first_and_last_names }}
{% endblock %} 
{% block content %}
    {% load thumbnail %}
    <div class="container py-5">        
        <h1>Все посты пользователя {{ user_object.get_full_name }} </h1>
        <h3>Всего постов: {{ user_object.posts_count }} </h3>
        {% if request.user.username != user_object.username%}
            {% if following %}
              <div class="mb-5">
                <a
                    class="btn btn-lg btn-secondary"
                    href="{% url 'posts:profile_unfollow' user_object.username %}" role="button"
                >
                Отписаться
                </a>
              </div>
            {% else %}
              <div class="mb-5">
                <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' user_object.username %}" role="button"
                >
                    Подписаться
                </a>
              </div>
            {% endif %}
        {% endif %}
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                Автор: <a href="{% url 'posts:profile' user_object.username %}">{{ user_object.get_full_name }}</a>
                </li>
                <li>
                Дата публикации: {{ post.pub_date|date:"j F Y" }}
                </li>
            </ul>
            <p>
                {% thumbnail post.image "1200x300" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}                
                {{ post.text|safe }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">Подробная информация о публикации</a>
        </article>
            {% if post.group %}   
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                    Все записи группы <b>{{ post.group.title }}</b> 
                </a>
            {% endif %}     
            {% if not forloop.last %}
                <hr>
            {% endif %}
    
    {% endfor%}
    
    {% include 'posts/includes/paginator.html' %}
    
    </div>
{% endblock %}